
shallow_clone: true # download the zip instead of the whole history

build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.10
      TARGET_ARCH: "x64"
      MINICONDA: C:\Miniconda3-x64
    - PYTHON_VERSION: 3.9
      TARGET_ARCH: "x64"
      MINICONDA: C:\Miniconda3-x64
    - PYTHON_VERSION: 3.8
      TARGET_ARCH: "x64"
      MINICONDA: C:\Miniconda3-x64
    - PYTHON_VERSION: 3.7
      TARGET_ARCH: "x64"
      MINICONDA: C:\Miniconda3-x64
    - PYTHON_VERSION: 3.6
      TARGET_ARCH: "x64"
      MINICONDA: C:\Miniconda3-x64
    - PYTHON_VERSION: 3.10
      TARGET_ARCH: "x86"
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.9
      TARGET_ARCH: "x86"
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.8
      TARGET_ARCH: "x86"
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.7
      TARGET_ARCH: "x86"
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.6
      TARGET_ARCH: "x86"
      MINICONDA: C:\Miniconda3

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% pandas matplotlib pytest"
  - activate test-environment
  - pip install -e .[extras]

test_script:
  - py.test -vv
  - set DSS_EXTENSIONS_DEBUG=1 && py.test -vv

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"
